version: "3"
services: 
    moobird:
        restart: always
        image: python:2.7.18
        volumes:
            - .:/src/
        command: bash -c "cd /src && /usr/local/bin/python -m pip install --upgrade pip && pip install -r requirements.txt && python mooBird.py"
