version: "3"
services: 
    moobird:
        container_name: beefy_moobird
        image: python:latest
        volumes:
            - .:/src/
        command: bash -c "python3 -m venv moobird-env && source moobird-env/bin/activate && cd /src && pip3 install -r requirements.txt && python main.py"
